# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-07 08:24
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userName', models.CharField(max_length=20)),
                ('userPwd', models.CharField(max_length=40)),
                ('userEmail', models.CharField(max_length=30)),
                ('userAddress', models.CharField(default='', max_length=100)),
                ('userTel', models.CharField(default='', max_length=11)),
                ('create_date', models.DateTimeField(db_column='ebf_html_create_date', default=datetime.datetime.utcnow)),
            ],
            options={
                'db_table': 'zw_user',
            },
        ),
    ]
